config = {
    "trigger_size": 4,
    "threshold": 0.5,
    "watermark_prefix": "my_seed",
    "num_layers": 5,
    "num_mlp_layers": 2,
    "hidden_dim": 64,
    "dropout": 0.5,
    "graph_pooling_type": "average",
    "learn_eps": False,
    "num_branches": 4,
    "gtn_layernum": 3,
    "target_label": 0,
    "watermark_client_frac": 0.0,
    "generator_lr": 0.01,
    "n_epoch": 5,
}
