config = {
    "bkd_gratio_train": 0.1,
    "bkd_gratio_test": 0.5,
    "bkd_size": 3,
    "bkd_num_pergraph": 1,
    "threshold": 0.5,
    "attack_client_frac": 0.0,
    "target_label": 0,
    "frac_of_avg": 0.3,
    "trigger_position": "cluster",
    "weight_threshold": 0.15,
    "target_loss_weight": 0.5,
    "homo_loss_weight": 0.5,
    "homo_boost_thrd": 0.8,
    "trojan_epochs": 500,
    "trojan_layernum": 2,
    "trojan_dropout": 0.0,
    "poisoning_intensity": 0.1,
}
