config = {
    "fedrgl_warmup_rounds": 10,
    "fedrgl_clean_scale": 0.5,
    "fedrgl_clean_scale_lp": 0.5,
    "fedrgl_lp_prop": 15,
    "fedrgl_lp_alpha": 0.5,
    "fedrgl_use_lp_filter": True,
    "fedrgl_only_stage1": False,
    "fedrgl_drop_feature_rate_1": 0.6,
    "fedrgl_drop_feature_rate_2": 0.6,
    "fedrgl_drop_edge_rate_1": 0.5,
    "fedrgl_drop_edge_rate_2": 0.5,
    "fedrgl_temperature": 0.5,
    "fedrgl_alpha_warmup": 0.0,
    "fedrgl_alpha_robust": 1.0,
    "fedrgl_mu_warmup": 1.5,
    "fedrgl_mu_robust": 1.5,
    "fedrgl_noisy_beta": 0.3,
    "fedrgl_js_weight": 0.4,
    "fedrgl_confidence_threshold": 0.8,
    "fedrgl_entropy_weight": True,
    "fedrgl_contrastive_max_nodes": 4096,
}
