config = {
    "params_weight": 'samples_num',
    "neibor_num": 3,
    "fggp_use_finch": False,
    "fggp_warmup_rounds": 30,
    "fggp_pseudo_confidence_threshold": 0.9,
    "fggp_use_pseudo_prototypes": True,
    "fggp_weighted_prototype_aggregation": True,
    "ce_weight": 1.0,
    "aug_ce_weight": 0.0,
    "ga_weight": 0.0,
    "pa_weight": 0.1,
    "kd_weight": 0.0,
    "kd_temperature": 0.1,
    "kd_detach_teacher": True,
    "global_proto_weight": 0.05,
    "global_proto_temperature": 0.2,
    "global_proto_mse_weight": 0.05,
    "use_fcpp_eval": False,
    "fcpp_temperature": 0.2,
    "fcpp_top_k": 30,
    "fcpp_model_logit_weight": 1.0,
    "fcpp_proto_logit_weight": 0.5,
}
